// Code generated by ogen, DO NOT EDIT.
package api

type CompleteOnboardingRes interface {
	completeOnboardingRes()
}

type ConvertNewsItemToArticleRes interface {
	convertNewsItemToArticleRes()
}

type GetContentRes interface {
	getContentRes()
}

type GetJobRes interface {
	getJobRes()
}

type GetNewsItemRes interface {
	getNewsItemRes()
}

type GetOnboardingRes interface {
	getOnboardingRes()
}

type ListContentRes interface {
	listContentRes()
}

type ListNewsItemsRes interface {
	listNewsItemsRes()
}

type ListSourcesRes interface {
	listSourcesRes()
}

type MarkNewsItemsReadRes interface {
	markNewsItemsReadRes()
}

type SearchAgentRes interface {
	searchAgentRes()
}

type StartOnboardingRes interface {
	startOnboardingRes()
}

type SubmitContentRes interface {
	submitContentRes()
}

type SubscribeSourceRes interface {
	subscribeSourceRes()
}
