// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CompleteOnboardingOperation       OperationName = "CompleteOnboarding"
	ConvertNewsItemToArticleOperation OperationName = "ConvertNewsItemToArticle"
	GetContentOperation               OperationName = "GetContent"
	GetJobOperation                   OperationName = "GetJob"
	GetNewsItemOperation              OperationName = "GetNewsItem"
	GetOnboardingOperation            OperationName = "GetOnboarding"
	ListContentOperation              OperationName = "ListContent"
	ListNewsItemsOperation            OperationName = "ListNewsItems"
	ListSourcesOperation              OperationName = "ListSources"
	MarkNewsItemsReadOperation        OperationName = "MarkNewsItemsRead"
	SearchAgentOperation              OperationName = "SearchAgent"
	StartOnboardingOperation          OperationName = "StartOnboarding"
	SubmitContentOperation            OperationName = "SubmitContent"
	SubscribeSourceOperation          OperationName = "SubscribeSource"
)
