[mcp_servers.XcodeBuildMCP]
command = "npx"
args = [ "-y", "xcodebuildmcp@latest", "mcp" ]

[mcp_servers.XcodeBuildMCP.env]
INCREMENTAL_BUILDS_ENABLED = "false"
XCODEBUILDMCP_SENTRY_DISABLED = "false"

[mcp_servers.pencil]
command = "/Applications/Pencil.app/Contents/Resources/app.asar.unpacked/out/mcp-server-darwin-arm64"
args = [ "--app", "desktop" ]
