[mcp_servers.XcodeBuildMCP]
command = "npx"
args = [ "-y", "xcodebuildmcp@latest", "mcp" ]

[mcp_servers.XcodeBuildMCP.env]
INCREMENTAL_BUILDS_ENABLED = "false"
XCODEBUILDMCP_SENTRY_DISABLED = "false"
