"""Add classification column to contents table

Revision ID: 200c2c1afb1b
Revises: 3de278fa5941
Create Date: 2025-06-17 20:38:04.844107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200c2c1afb1b'
down_revision: Union[str, None] = '3de278fa5941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('classification', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_contents_classification'), 'contents', ['classification'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_classification'), table_name='contents')
    op.drop_column('contents', 'classification')
    # ### end Alembic commands ###
