"""Add source column to Content model

Revision ID: 3de278fa5941
Revises: 
Create Date: 2025-06-15 14:03:02.127824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de278fa5941'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('source', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_contents_source'), 'contents', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contents_source'), table_name='contents')
    op.drop_column('contents', 'source')
    # ### end Alembic commands ###
