"""Add EventLog table for generic event logging

Revision ID: 65a196dd7bed
Revises: 8c77d2e90882
Create Date: 2025-06-19 20:52:29.730854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a196dd7bed'
down_revision: Union[str, None] = '8c77d2e90882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_name_created', 'event_logs', ['event_name', 'created_at'], unique=False)
    op.create_index('idx_event_status_created', 'event_logs', ['event_type', 'status', 'created_at'], unique=False)
    op.create_index('idx_event_type_created', 'event_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_created_at'), 'event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_logs_event_name'), 'event_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_logs_status'), 'event_logs', ['status'], unique=False)
    op.create_index(op.f('ix_scraper_runs_status'), 'scraper_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraper_runs_status'), table_name='scraper_runs')
    op.drop_index(op.f('ix_event_logs_status'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_event_name'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_created_at'), table_name='event_logs')
    op.drop_index('idx_event_type_created', table_name='event_logs')
    op.drop_index('idx_event_status_created', table_name='event_logs')
    op.drop_index('idx_event_name_created', table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
