"""Add scraper_runs table for tracking scraper execution statistics

Revision ID: 8c77d2e90882
Revises: 200c2c1afb1b
Create Date: 2025-06-19 16:11:23.169495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c77d2e90882'
down_revision: Union[str, None] = '200c2c1afb1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_scraped', sa.Integer(), nullable=True),
    sa.Column('total_saved', sa.Integer(), nullable=True),
    sa.Column('total_duplicates', sa.Integer(), nullable=True),
    sa.Column('total_errors', sa.Integer(), nullable=True),
    sa.Column('scraper_stats', sa.JSON(), nullable=True),
    sa.Column('processing_stats', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_started', 'scraper_runs', ['started_at'], unique=False)
    op.create_index('idx_run_status', 'scraper_runs', ['status'], unique=False)
    op.create_index('idx_run_type_started', 'scraper_runs', ['run_type', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_run_type_started', table_name='scraper_runs')
    op.drop_index('idx_run_status', table_name='scraper_runs')
    op.drop_index('idx_run_started', table_name='scraper_runs')
    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
