#!/bin/bash
# sync-secrets.sh
# Syncs API keys from the root .env file to Secrets.xcconfig
#
# Usage: ./sync-secrets.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
SECRETS_FILE="$SCRIPT_DIR/Secrets.xcconfig"

if [ ! -f "$ENV_FILE" ]; then
    echo "Error: .env file not found at $ENV_FILE"
    exit 1
fi

# Extract OpenAI API key from .env
OPENAI_KEY=$(grep "^OPENAI_API_KEY=" "$ENV_FILE" | cut -d'=' -f2-)

if [ -z "$OPENAI_KEY" ]; then
    echo "Error: OPENAI_API_KEY not found in .env"
    exit 1
fi

# Write to Secrets.xcconfig
cat > "$SECRETS_FILE" << EOF
// Secrets.xcconfig
// Auto-generated by sync-secrets.sh - DO NOT COMMIT TO GIT
//
// To regenerate, run: ./sync-secrets.sh

// OpenAI API Key for voice dictation (gpt-4o-transcribe)
OPENAI_API_KEY = $OPENAI_KEY
EOF

echo "✓ Synced OPENAI_API_KEY to Secrets.xcconfig"
echo "  Source: $ENV_FILE"
echo "  Target: $SECRETS_FILE"
